test_task:
  container:
    image: docker.io/cimg/rust:1.88.0
  test_script: cargo test

task:
  name: build-amd64linux
  container:
    image: docker.io/cimg/rust:1.88.0
  script:
    - rustup target add x86_64-unknown-linux-musl
    - cargo xtask build x86_64-unknown-linux-musl
  artifacts:
    path: bins/*

task:
  name: build-aarch64darwin
  macos_instance:
    image: ghcr.io/cirruslabs/macos-runner:sonoma
  env: 
    PATH: $HOME/.cargo/bin:$PATH
  deps_script:
    - curl -proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh
    - sh rustup.sh -qy
  build_script:
    - rustup target add aarch64-apple-darwin
    - cargo xtask build aarch64-apple-darwin
  artifacts:
    path: bins/*

