test_task:
  container:
    image: docker.io/cimg/rust:1.88.0
  test_script: cargo test

task:
  name: build-amd64linux
  container:
    image: docker.io/cimg/rust:1.88.0
  script:
    - rustup target add x86_64-unknown-linux-musl
    - cargo xtask build x86_64-unknown-linux-musl
  artifacts:
    path: "bins/*"

