test_task:
  container:
    image: docker.io/cimg/rust:1.88.0
  test_script: cargo test

task:
  name: build-darwin
  depends_on:
    - test
  macos_instance:
    image: ghcr.io/cirruslabs/macos-runner:sonoma
  env: 
    PATH: $HOME/.cargo/bin:$PATH
  deps_script:
    - curl -proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh
    - sh rustup.sh -qy
    - rustup target add aarch64-apple-darwin
    - cargo install cross
  build_script:
    - cargo xtask build aarch64-apple-darwin
  artifacts:
    path: bins/*



docker_builder:
  name: build-linux-freebsd-illumos
  deps_script:
    - curl -proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh
    - sh rustup.sh -qy
    - rustup target add x86_64-unknown-linux-musl
    - rustup target add aarch64-unknown-linux-musl
    - rustup target add x86_64-unknown-freebsd
    - rustup target add x86_66-unknown-illumos
    - cargo install cross
  build_script:
    - cargo xtask build x86_64-unknown-linux-musl
    - cargo xtask build aarch64-unknown-linux-musl
    - cargo xtask build x86_64-unknown-freebsd
    - cargo xtask build x86_64-unknown-illumos
  artifacts:
    path: bins/*

