[package]
name = "theseus"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.87", default-features = false, features = ["std"] }
blake3 = { version = "1.5.4", default-features = false, features = ["std"] }
clap = { version = "4.5.17", default-features = false, features = ["derive", "help", "std"] }
env_logger = { version = "0.11.5", default-features = false }
log = { version = "0.4.22", default-features = false }
nix = { version = "0.29.0", default-features = false, features = ["fs", "user", "feature"] }
postcard = { version = "1.0.10", default-features = false, features = ["use-std", "alloc"] }
serde = { version = "1.0.210", default-features = false, features = ["serde_derive", "default", "alloc"] }
serde_bytes = { version = "0.11.15", default-features = false }
tar = { version = "0.4.41", default-features = false }
thiserror = { version = "1.0.63", default-features = false }
toml = { version = "0.8.19", default-features = false, features = ["display", "parse"] }
zstd = { version = "0.13.2", default-features = false }

[[bin]]
name = "theseusd"
path = "src/daemon.rs"

[[bin]]
name = "theseus"
path = "src/wizard.rs"

[profile.release]
opt-level = 3
lto = "fat"

