FROM docker.io/cimg/rust:1.88.0

RUN sudo apt-get update && \
    sudo apt-get install qemu -y && \
    sudo apt-get clean

ENV CROSS_CONTAINER_IN_CONTAINER=true
RUN cargo install cross
RUN rustup target add x86_64-unknown-linux-musl  \
                      aarch64-unknown-linux-musl \
                      x86_64-unknown-freebsd     \
                      x86_64-unknown-illumos

