FROM docker.io/cimg/rust:1.88.0

RUN sudo apt install qemu 

ENV CROSS_CONTAINER_IN_CONTAINER=true
RUN cargo install cross
RUN rustup target add x86_64-unknown-linux-musl  \
                      aarch64-unknown-linux-musl \
                      x86_64-unknown-illumos

